# Generated by Django 5.2.1 on 2025-05-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_orderitem_order_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
